# Generated by Django 4.2.2 on 2023-06-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', 'initial_added_emotional_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionalstate',
            old_name='coping_mechanism',
            new_name='coping_mechanisms',
        ),
    ]
