# Generated by Django 4.2.2 on 2023-07-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_emotionalstate_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionalstate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
